# Generated by Django 4.2.15 on 2024-10-10 16:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='form_img')),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HassasiyetTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hastalik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hatirlatici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('form', models.CharField(blank=True, max_length=50, null=True)),
                ('kuvvet', models.CharField(blank=True, max_length=50, null=True)),
                ('baslangic_tarihi', models.DateField(blank=True, null=True)),
                ('bitis_tarihi', models.DateField(blank=True, null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('is_stopped', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hatirlatici_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ilac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('etken_madde', models.CharField(blank=True, max_length=200, null=True)),
                ('kullanim_uyarisi', models.CharField(blank=True, max_length=300, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents')),
                ('kontsantrasyon_ml', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('kontsantrasyon_mg', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('hassasiyet_turu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appname.hassasiyetturu')),
                ('hastaliklar', models.ManyToManyField(related_name='ilaclar', to='appname.hastalik')),
                ('ilac_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appname.form')),
            ],
        ),
        migrations.CreateModel(
            name='IlacKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='ilac_kategori_img')),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='supplement_img')),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YasDoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doz', models.CharField(blank=True, max_length=400, null=True)),
                ('min_yas', models.IntegerField()),
                ('maks_yas', models.IntegerField()),
                ('ilac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('supplement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appname.supplement')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appname.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2024, 10, 10, 16, 45, 40, 303490, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KiloDoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanim_sikligi', models.CharField(blank=True, max_length=150, null=True)),
                ('check_uyari', models.TextField(blank=True, null=True)),
                ('tipik_min_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('tipik_max_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('maksimum_anlik_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('ilac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac')),
            ],
        ),
        migrations.AddField(
            model_name='ilac',
            name='ilac_kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appname.ilackategori'),
        ),
        migrations.CreateModel(
            name='HatirlaticiSaati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saat', models.TimeField(blank=True, null=True)),
                ('hatirlatici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hatirlatici_saat', to='appname.hatirlatici')),
            ],
        ),
        migrations.CreateModel(
            name='HatalikYasDoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doz', models.CharField(blank=True, max_length=200, null=True)),
                ('min_yas', models.IntegerField()),
                ('maks_yas', models.IntegerField()),
                ('hastaliklar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hastalikyasdoz', to='appname.hastalik')),
                ('ilac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac')),
            ],
        ),
        migrations.CreateModel(
            name='HastalikKiloDoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanim_sikligi', models.CharField(blank=True, max_length=150, null=True)),
                ('check_uyari', models.TextField(blank=True, null=True)),
                ('tipik_min_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('tipik_max_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('maksimum_anlik_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('hastaliklar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hastalikkilodoz', to='appname.hastalik')),
                ('ilac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac')),
            ],
        ),
        migrations.CreateModel(
            name='HastalikHemYasaHemKiloyaBagliAzalanDoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanim_sikligi', models.CharField(blank=True, max_length=150, null=True)),
                ('check_uyari', models.TextField(blank=True, null=True)),
                ('tipik_min_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('tipik_max_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('threshold_age', models.IntegerField()),
                ('threshold_age_min_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('threshold_age_max_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('hastaliklar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hastalikhemyasahemkiloyabagliazalandoz', to='appname.hastalik')),
                ('ilac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac')),
            ],
        ),
        migrations.CreateModel(
            name='HastalikHemYasaHemKiloyaBagliArtanDoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanim_sikligi', models.CharField(blank=True, max_length=150, null=True)),
                ('check_uyari', models.TextField(blank=True, null=True)),
                ('tipik_min_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('tipik_max_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('maksimum_anlik_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('threshold_age', models.IntegerField()),
                ('threshold_age_min_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('threshold_age_max_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('hastaliklar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hastalikhemyasahemkiloyabagliartandoz', to='appname.hastalik')),
                ('ilac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac')),
            ],
        ),
        migrations.CreateModel(
            name='HastalikAzalanKiloDoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanim_sikligi', models.CharField(blank=True, max_length=150, null=True)),
                ('check_uyari', models.TextField(blank=True, null=True)),
                ('tipik_min_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('tipik_max_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('threshold_weight', models.IntegerField()),
                ('threshold_weight_min_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('threshold_weight_max_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('hastaliklar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hastalikazalankilodoz', to='appname.hastalik')),
                ('ilac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac')),
            ],
        ),
        migrations.CreateModel(
            name='HastalikArtanKiloDoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanim_sikligi', models.CharField(blank=True, max_length=150, null=True)),
                ('check_uyari', models.TextField(blank=True, null=True)),
                ('tipik_min_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('tipik_max_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('maksimum_anlik_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('threshold_weight', models.IntegerField()),
                ('threshold_weight_min_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('threshold_weight_max_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('hastaliklar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hastalikartankilodoz', to='appname.hastalik')),
                ('ilac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac')),
            ],
        ),
        migrations.CreateModel(
            name='ExplanationDoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilgi', models.TextField(blank=True, null=True)),
                ('ilac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac')),
            ],
        ),
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saat', models.TimeField(blank=True, null=True)),
                ('explanations', models.TextField(blank=True, null=True)),
                ('tarih', models.DateField(blank=True, null=True)),
                ('durum', models.BooleanField(default=False)),
                ('hatirlatici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hatirlatici_bildirim', to='appname.hatirlatici')),
            ],
        ),
        migrations.CreateModel(
            name='AzalanKiloDoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanim_sikligi', models.CharField(blank=True, max_length=150, null=True)),
                ('check_uyari', models.TextField(blank=True, null=True)),
                ('tipik_min_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('tipik_max_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('threshold_weight', models.IntegerField()),
                ('threshold_weight_min_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('threshold_weight_max_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('ilac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac')),
            ],
        ),
        migrations.CreateModel(
            name='ArtanKiloDoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanim_sikligi', models.CharField(blank=True, max_length=150, null=True)),
                ('check_uyari', models.TextField(blank=True, null=True)),
                ('tipik_min_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('tipik_max_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('maksimum_anlik_doz', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('threshold_weight', models.IntegerField()),
                ('threshold_weight_min_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('threshold_weight_max_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('ilac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac')),
            ],
        ),
        migrations.AddIndex(
            model_name='hatirlatici',
            index=models.Index(fields=['user', 'is_removed', 'baslangic_tarihi', 'bitis_tarihi'], name='appname_hat_user_id_8b784a_idx'),
        ),
        migrations.AddIndex(
            model_name='hatirlatici',
            index=models.Index(fields=['id'], name='appname_hat_id_c2bcab_idx'),
        ),
    ]
