# Generated by Django 4.2.15 on 2024-10-10 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 17, 36, 37, 506093, tzinfo=datetime.timezone.utc)),
        ),
    ]
