# Generated by Django 4.2.15 on 2024-10-11 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 11, 11, 34, 55, 877348, tzinfo=datetime.timezone.utc)),
        ),
    ]
