# Generated by Django 4.2.15 on 2024-10-13 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='satin_al_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 15, 12, 8, 800117, tzinfo=datetime.timezone.utc)),
        ),
    ]
